[profile.default]
optimizer = true
optimizer_runs = 2500
remappings = [
  "@uniswap/v4-core/=lib/v4-core/",
  "solmate/src/=lib/solmate/src/",
  "solmate/utils/=lib/solmate/src/utils/",
]
solc_version = "0.8.30"
verbosity = 1
via_ir = true

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[profile.gas]
optimizer_runs = 100_000_000

[profile.hub_logic]
optimizer_runs = 5000 # optimal

[profile.hook_logic]
optimizer_runs = 2500 # optimal

[profile.hub]
optimizer_runs = 100_000_000 # optimal

[profile.hook]
optimizer_runs = 2000 # optimal

[profile.quoter]
optimizer_runs = 10_000

[rpc_endpoints]
arbitrum = "${RPC_URL_ARBITRUM}"
avalanche = "${RPC_URL_AVALANCHE}"
base = "${RPC_URL_BASE}"
bsc = "${RPC_URL_BSC}"
mainnet = "${RPC_URL_MAINNET}"
optimism = "${RPC_URL_OPTIMISM}"
polygon = "${RPC_URL_POLYGON}"
sepolia = "${RPC_URL_SEPOLIA}"
unichain = "${RPC_URL_UNICHAIN}"

[etherscan]
arbitrum = {key = "${ETHERSCAN_KEY}"}
avalanche = {key = "${ETHERSCAN_KEY}"}
base = {key = "${ETHERSCAN_KEY}"}
bsc = {key = "${ETHERSCAN_KEY}"}
mainnet = {key = "${ETHERSCAN_KEY}"}
optimism = {key = "${ETHERSCAN_KEY}"}
polygon = {key = "${ETHERSCAN_KEY}"}
sepolia = {key = "${ETHERSCAN_KEY}"}
unichain = {key = "${ETHERSCAN_KEY}"}
