[profile.default]
cancun = true
optimizer_runs = 1000000
remappings = [
  "@uniswap/v4-core/src/=lib/v4-core/src/",
  "@uniswap/v4-periphery/=lib/v4-periphery/",
  "@uniswap/v4-core/contracts/=lib/v4-core/src/",
]
solc = "./lib/v4-core/bin/solc-mac"
verbosity = 1
via_ir = true

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
mainnet = {key = "${ETHERSCAN_KEY}"}
