[profile.default]
evm_version = "cancun"
optimizer = true
optimizer_runs = 7500
remappings = [
  "@uniswap/v4-core/=lib/v4-core/",
  "solmate/src/=lib/solmate/src/",
  "solmate/utils/=lib/solmate/src/utils/",
]
solc_version = "0.8.25"
verbosity = 1
via_ir = true

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[profile.gas]
optimizer_runs = 100_000_000
solc_version = "0.8.28"

[rpc_endpoints]
arbitrum = "${RPC_URL_ARBITRUM}"
avalanche = "${RPC_URL_AVALANCHE}"
base = "${RPC_URL_BASE}"
bsc = "${RPC_URL_BSC}"
mainnet = "${RPC_URL_MAINNET}"
optimism = "${RPC_URL_OPTIMISM}"
polygon = "${RPC_URL_POLYGON}"
sepolia = "${RPC_URL_SEPOLIA}"

[etherscan]
arbitrum = {key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api"}
avalanche = {key = "${SNOWTRACE_KEY}", url = "https://api.snowtrace.io/api"}
base = {key = "${BASESCAN_KEY}", url = "https://api.basescan.org/api"}
bsc = {key = "${BSCSCAN_KEY}", url = "https://api.bscscan.com/api"}
mainnet = {key = "${ETHERSCAN_KEY}"}
optimism = {key = "${OPTIMISM_ETHERSCAN_KEY}", url = "https://api-optimistic.etherscan.io/api"}
polygon = {key = "${POLYGONSCAN_KEY}", url = "https://api.polygonscan.com/api"}
sepolia = {key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api"}
